### PR TITLE
ConfigParser: do NOT override existing sections

### PR DESCRIPTION
**Pull request by wongsyrone**
This commit support format as below:

```
[DNS]
EQUAL,example.com

[URL]
PREFIX,https://example.com/a

[URL]
PREFIX,https://example.com/foo

[URL]
PREFIX,https://example.com/bar
```

It merges sections with the same section name.

### CODE REVIEW

**Comment by wongsyrone** [comment]
Before this commit, the above config is eventually equivalent to:

```
[DNS]
EQUAL,example.com

#[URL]
#PREFIX,https://example.com/a

#[URL]
#PREFIX,https://example.com/foo

[URL]
PREFIX,https://example.com/bar
```

Otherwise, let's "fix" it.

```
[DNS]
EQUAL,example.com

[URL]
PREFIX,https://example.com/a
PREFIX,https://example.com/foo
PREFIX,https://example.com/bar
```

**Comment by pengzhile** [comment]
because the plugin mechanism was added later, this config format may not be appropriate. so I will restructure it into a more suitable format.

**Comment by wongsyrone** [comment]
Thanks.

**Comment by wongsyrone** [comment]
>  为什么不试试putIfAbsent或者computeIfAbsent呢

都可以，没想优化的事，先能用再说

**Pull request merged**
